[general]
import = [
  "~/.config/alacritty/lavi.toml",
]

[window]
dimensions = { columns = 115, lines = 30 }
decorations = "Full"
padding = { x = 8, y = 8 }
opacity = 0.3
blur = true

[font]
normal = { family = "MapleMono NF", style = "Regular" }
bold = { family = "MapleMono NF", style = "Bold" }
italic = { family = "MapleMono NF", style = "Italic" }
bold_italic = { family = "MapleMono NF", style = "Bold Italic" }
size = 12

[terminal]
shell = "/usr/bin/fish"

[cursor]
style = { shape = "Beam", blinking = "On" }

