name: forgejo
services:
  server:
    image: codeberg.org/forgejo/forgejo:14
    container_name: forgejo
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - forgejo
      - proxy_network
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - forgejo_data:/data
    ports:
      - '3000:3000'
      - '3001:22'

networks:
  forgejo:
    external: false
  proxy_network:
    external: true

volumes:
  forgejo_data:
